export const dataTable = [
  {
    headline: "Increasing call volume analysis",
    type: "Performance",
    status: "prioritised",
    for: "Expert",
    dueName: "ope",
    dueColor: "#d31464eb",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "1",
    color: "info",
    id: "1",
    width: "300px",
  },
  {
    headline: "New product buyer profilling",
    type: "Performance",
    status: "prioritised",
    for: "Proposer",
    dueName: "cor",
    dueColor: "#aef92c8f",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "2",
    color: "info",
    id: "2",
    width: "50px",
  },
  {
    headline: "M&A Analysis - CEO request",
    type: "-",
    status: "wishlist",
    for: "Proposer",
    dueName: "ope",
    dueColor: "#d31464eb",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "1",
    color: "warning",
    id: "3",
    width: "125px",
  },
  {
    headline: "Faud in cident detected",
    type: "Reporting",
    status: "prioritised",
    for: "Proposer",
    dueName: "ret",
    dueColor: "#1c39e9c2",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "3",
    color: "info",
    id: "4",
    width: "125px",
  },
  {
    headline: "Update to Sales reports",
    type: "Insights Analytics",
    status: "wishlist",
    for: "Expert",
    dueName: "sys",
    dueColor: "#340697f0",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "4",
    color: "warning",
    id: "5",
    width: "125px",
  },
  {
    headline: "1",
    type: "Insights Analytics",
    status: "wishlist",
    for: "Proposer",
    dueName: "sys",
    dueColor: "#340697f0",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "1",
    color: "warning",
    id: "6",
    width: "200px",
  },
  {
    headline: "Mobile plan rationalisation project",
    type: "Reporting",
    status: "prioritised",
    for: "Expert",
    dueName: "r&d",
    dueColor: "#92c33ddb",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "1",
    color: "info",
    id: "7",
    width: "50px",
  },
  {
    headline: "Sales growth opportunities",
    type: "Reporting",
    status: "wishlist",
    for: "Expert",
    dueName: "bus",
    dueColor: "#d1230ced",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "2",
    color: "warning",
    id: "8",
    width: "200px",
  },
  {
    headline: "Sales growth opportunities",
    type: "-",
    status: "planned",
    for: "Expert",
    dueName: "bus",
    dueColor: "#d1230ced",
    typeColor: "#8bb4ff",
    planned: "29/04/2022",
    assigned: "-",
    effort: "-",
    business: "3",
    color: "secondary",
    id: "9",
    width: "200px",
  },
];
export const dataTableHeader = [
  {
    name: "headline",
    width: "300px",
  },
  {
    name: "type",
    width: "125px",
  },
  {
    name: "status",
    width: "85px",
  },
  {
    name: "for",
    width: "125px",
  },
  {
    name: "due",
    width: "125px",
  },
  {
    name: "planned",
    width: "180px",
  },
  {
    name: "assigned",
    width: "80px",
  },
  {
    name: "effort",
    width: "80px",
  },
  {
    name: "business",
    width: "130px",
  },
];
